version: "3.7"

services:
  client:
    container_name: client
    build: ./client/
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    ports:
      - "8080:8080"
    environment:
      VUE_APP_GRAPHQL_HTTP: "http://localhost:4000/graphql"
      VUE_APP_GRAPHQL_WS: "http://localhost:4000/graphql"
  server:
    container_name: server
    build: ./server/
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    ports:
      - "4000:4000"
